In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
df1 = pd.read_csv('house_prices (2).csv')
df1.head()

,sqft_living,bedrooms,bathrooms,floors,house_age,dist_to_city_km,quality_score,price
0,959,4,2.0,2.0,10,13.97,6,256153
1,3173,4,2.6,2.0,9,1.40,4,602494
2,2017,1,1.9,1.0,71,0.24,9,403973
3,818,5,3.7,1.5,45,13.07,3,208514
4,2036,3,2.3,2.0,57,1.90,5,396980

In [ ]:
df1.shape

(1000, 8)

In [ ]:
df1.describe()

,sqft_living,bedrooms,bathrooms,floors,house_age,dist_to_city_km,quality_score,price
count,1000.000000,1000.000000,988.000000,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03
mean,1872.225000,3.368000,2.528745,1.621500,19.530000,8.020810,6.581000,4.081768e+05
std,721.658094,1.189955,0.963300,0.613077,18.964882,7.635918,2.240638,1.518990e+05
min,450.000000,1.000000,1.000000,1.000000,0.000000,0.200000,3.000000,8.956100e+04
25%,1362.000000,3.000000,1.800000,1.000000,6.000000,2.327500,5.000000,3.257180e+05
50%,1873.500000,3.000000,2.500000,1.500000,13.000000,5.690000,7.000000,4.020970e+05
75%,2358.000000,4.000000,3.100000,2.000000,27.000000,11.495000,9.000000,4.792382e+05
max,3927.000000,6.000000,5.000000,3.000000,100.000000,46.160000,10.000000,2.558280e+06

In [ ]:
df1.isnull().sum()

sqft_living         0
bedrooms            0
bathrooms          12
floors              0
house_age           0
dist_to_city_km     0
quality_score       0
price               0
dtype: int64

In [ ]:
df1['bathrooms']=df1['bathrooms'].fillna(df1['bathrooms'].median())
df1.isnull().sum()

sqft_living        0
bedrooms           0
bathrooms          0
floors             0
house_age          0
dist_to_city_km    0
quality_score      0
price              0
dtype: int64

In [ ]:
q1 = df1['price'].quantile(0.25)
q3 = df1['price'].quantile(0.75)
iqr = q3-q1
upper=q3+3*iqr
df1=df1[df1['price']<upper]
df1.shape

(997, 8)

In [ ]:
x=df1.drop(columns = 'price')
y = df1['price']
print(x)
print(y)

     sqft_living  bedrooms  bathrooms  floors  house_age  dist_to_city_km  \
0            959         4        2.0     2.0         10            13.97
1           3173         4        2.6     2.0          9             1.40
2           2017         1        1.9     1.0         71             0.24
3            818         5        3.7     1.5         45            13.07
4           2036         3        2.3     2.0         57             1.90
..           ...       ...        ...     ...        ...              ...
995         2530         2        1.5     2.0          2             6.32
996         1159         3        2.1     2.5         12             1.00
997         2530         3        2.1     1.5         37             3.36
998          785         1        1.0     3.0          4             0.77
999         3076         3        2.2     2.0         19             5.67

     quality_score
0                6
1                4
2                9
3                3
4                5
..             ...
995              3
996              5
997              9
998              5
999              6

[997 rows x 7 columns]
0      256153
1      602494
2      403973
3      208514
4      396980
        ...
995    442706
996    290977
997    512494
998    242206
999    574995
Name: price, Length: 997, dtype: int64

In [ ]:
scaler=StandardScaler()

In [ ]:
scaler.fit(x)
X_std=scaler.transform(x)
print(X_std)

[[-1.26516212  0.5313711  -0.55215823 ... -0.50272299  0.77894603
  -0.26273531]
 [ 1.80119768  0.5313711   0.07436122 ... -0.55543805 -0.86580809
  -1.15675274]
 [ 0.20015345 -1.99137647 -0.65657814 ...  2.71289585 -1.01759129
   1.07829083]
 ...
 [ 0.91065145 -0.30954475 -0.44773833 ...  0.92058371 -0.60934683
   1.07829083]
 [-1.50614974 -1.99137647 -1.59635732 ... -0.81901336 -0.94824207
  -0.70974402]
 [ 1.666854   -0.30954475 -0.34331842 ... -0.02828742 -0.30708891
  -0.26273531]]

In [ ]:
X=X_std

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [ ]:
print(x.shape,x_train.shape,x_test.shape)

(997, 7) (797, 7) (200, 7)

In [ ]:
cf2=RandomForestRegressor(n_estimators=200,max_depth=10,random_state=2)
cf2.fit(x_train,y_train)

RandomForestRegressor(max_depth=10, n_estimators=200, random_state=2)

In [ ]:
x_train_pred=cf2.predict(x_train)
train_score=r2_score(y_train,x_train_pred)
print(train_score)

0.9914272926864008

In [ ]:
x_test_pred=cf2.predict(x_test)
test_score=r2_score(y_test,x_test_pred)
print(test_score)

0.9438451796541517

In [ ]:
data2=[2150,3,2.0,8,5,4,7]
print(data2)

[2150, 3, 2.0, 8, 5, 4, 7]

In [ ]:
data_np=np.asarray(data2)
print(data_np)

[2.15e+03 3.00e+00 2.00e+00 8.00e+00 5.00e+00 4.00e+00 7.00e+00]

In [ ]:
data_reshape=data_np.reshape(1,-1)

In [ ]:
input_std=scaler.transform(data_reshape)
print(input_std)

[[ 0.38435664 -0.30954475 -0.55215823 10.41275705 -0.7662983  -0.52560437
   0.1842734 ]]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [ ]:
predict=cf2.predict(input_std)
print(predict)

[460258.67371491]